data_dirs: [
  /cs/dataset/Download/adiyoss/heb_data/hayot-kis-gold-prepared/valle/,
  /cs/dataset/Download/adiyoss/heb_data/osim-history-prepared/valle/
]
data_root: /cs/dataset/Download/adiyoss/heb_data/
spkr_name_getter: "lambda p: p.parts[-3]"

model: ar
batch_size: 6
eval_batch_size: 6
eval_every: 10_000

sampling_temperature: 1.0
