prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/prepared_valle_data"
datasets:
  -
    name: "hayot-kis-gold"
    prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/hayot-kis-gold-prepared/valle/"
    original_wav_path: "/cs/dataset/Download/adiyoss/podcasts/hayot_kis/saspeech_gold_standard/wavs_24k/"
    metadata_path: "/cs/dataset/Download/adiyoss/podcasts/hayot_kis/saspeech_gold_standard/metadata.csv"
    labeled: True
    length: 0
  -
    name: "osim-history"
    prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/osim-history-prepared/valle/"
    original_wav_path: "/cs/dataset/Download/adiyoss/podcasts/parsed_data/osim-history/"
    metadata_path: "/cs/dataset/Download/adiyoss/heb_data/osim-history-prepared/metadata/"
    labeled: False
    length: 250  # Hours
  -
    name: "geekonomy"
    prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/geekonomy-prepared/valle/"
    original_wav_path: "/cs/dataset/Download/adiyoss/podcasts/parsed_data/geekonomy/"
    metadata_path: "/cs/dataset/Download/adiyoss/heb_data/geekonomy-prepared/metadata/"
    labeled: False
    length: 1200  # Hours

