prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/prepared_valle_data"
datasets:
  -
    name: "test"
    prepared_data_path: "/Users/amitroth/Data/prepared_data/valle/"
    original_wav_path: "/Users/amitroth/Data/raw_data"
    metadata_path: "/Users/amitroth/Data/prepared_data/metadata/"
    labeled: False
    length: 250  # Hours
  -
    name: "osim-history"
    prepared_data_path: "/cs/dataset/Download/adiyoss/heb_data/osim-history-prepared/valle/"
    original_wav_path: "/cs/dataset/Download/adiyoss/podcasts/parsed_data/osim-history/"
    metadata_path: "/cs/dataset/Download/adiyoss/heb_data/osim-history-prepared/metadata/"
    labeled: False
    length: 250  # Hours


