data_dirs: [/cs/dataset/Download/adiyoss/heb_data/saspeech_valle]
data_root: /cs/dataset/Download/adiyoss/heb_data/
spkr_name_getter: "lambda p: p.parts[-3]"

model: ar
batch_size: 32
eval_batch_size: 24
eval_every: 10_000

sampling_temperature: 1.0
