

# For inference
output_path: "/cs/labs/adiyoss/amitroth/vall-e/output/saspeech"
ar_ckpt_path: "/cs/labs/adiyoss/amitroth/vall-e/zoo/saspeech/ar.pt"
nar_ckpt_path: "/cs/labs/adiyoss/amitroth/vall-e/zoo/saspeech/nar.pt"
reference_path_hayot: "/cs/labs/adiyoss/amitroth/vall-e/data/reference/saspeech/hayot.wav"
reference_path_amit: "/cs/labs/adiyoss/amitroth/vall-e/data/reference/saspeech/amit.wav"
reference_path_shahar: "/cs/labs/adiyoss/amitroth/vall-e/data/reference/saspeech/shahar.wav"



# For ckpts
latest_ar_path: "/cs/labs/adiyoss/amitroth/vall-e/ckpts/saspeech/ar/model/latest"
latest_nar_path: "/cs/labs/adiyoss/amitroth/vall-e/ckpts/saspeech/nar/model/latest"
