data_dirs: [/cs/dataset/Download/adiyoss/heb_data/saspeech_valle]
data_root: /cs/dataset/Download/adiyoss/heb_data/
spkr_name_getter: "lambda p: p.parts[-3]"

model: nar
batch_size: 22
eval_batch_size: 22
eval_every: 10_000

sampling_temperature: 0.2
